version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
