# Generated by Django 2.1.1 on 2018-09-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20180924_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lineitem_order_created', to='Market.Order'),
        ),
    ]
